[env:pickle_flow]
platform = espressif32
board = esp32-s3-touchlcd-2
framework = arduino
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -D LV_CONF_INCLUDE_SIMPLE=1
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -Iinclude
lib_deps =
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.3
    lvgl/lvgl @ ^8.3.11
    https://github.com/lovyan03/LovyanGFX.git
    https://github.com/CIRCUITSTATE/CSE_Touch.git
    https://github.com/CIRCUITSTATE/CSE_CST328.git
